### PR TITLE
add multi channel support

### PR DESCRIPTION
**Pull request by rickwalder**
tested working

### CODE REVIEW

**Comment by rickwalder** [comment]
this is good to go. Got confused by a ... in readme, it’s set back to how it should be

**Review by BrendanSweeny — APPROVED** [review]
Looks good. I haven't used any controllers with support for instances other than 1, but I'm happy to add support for them. Thanks for contributing!

**Comment by rickwalder** [comment]
Happy to help 👍 

for posterity, I am using this to read and write temp, heater power, and set point from a RMA and two RMH’s from the EZ Zone RM series (https://www.watlow.com/products/controllers/ez-zone-rm-modules)

**Comment by BrendanSweeny** [comment]
I'm thrilled its working for you. By comparison, I'm running a pretty simple setup that consists of a handful of EZ Zone panel mount controllers. Anyway, build 0.1.2 is on PyPI.

**Pull request merged**
